#!/bin/bash

# Set the environment variable SCMUTILS_ROOT to override the default
# location for the scmutils root directory.
ROOT="${SCMUTILS_ROOT:-/usr/local/scmutils}"
EDWIN_INFO_DIRECTORY="${ROOT}/mit-scheme/lib/edwin/info"
SCHEME="${ROOT}/mit-scheme/bin/scheme --library ${ROOT}/mit-scheme/lib"
