#!/bin/bash

# SCHEME="/usr/local/mit-scheme/bin/mit-scheme"

ROOT="${SCMUTILS_ROOT:-/usr/local/scmutils}"
SCHEME="${ROOT}/mit-scheme/bin/scheme --library ${ROOT}/mit-scheme/lib"

rm -f $1
touch $1
tail -f $1 --pid=$$ 1>&2 & exec ${SCHEME} --load $2 --args $1
