#!/bin/sh

SERVER=./server.js

SCHEME_PATH=./start-mechanics-in-chroot-jail

ABSOLUTE_JAIL_ROOT=/home/scmutils-server-root/
RELATIVE_JAIL_ROOT=home/scheme-user/

LOAD_PATH=${RELATIVE_JAIL_ROOT}utils/load.scm
PIPE_DIRECTORY=${RELATIVE_JAIL_ROOT}pipes/

node ${SERVER} ${SCHEME_PATH} ${ABSOLUTE_JAIL_ROOT} ${LOAD_PATH} ${PIPE_DIRECTORY}
