#!/bin/bash

# Set the environment variable SCMUTILS_ROOT to override the default
# location for the scmutils root directory.
ROOT="${SCMUTILS_ROOT:-/usr/local/scmutils}"
SCHEME="${ROOT}/mit-scheme/bin/scheme --library ${ROOT}/mit-scheme/lib"

exec ${SCHEME}
