#!/bin/bash

# Set the environment variable SCMUTILS_ROOT to override the default
# location for the scmutils root directory.
ROOT="/usr/local"
SCMUTILS_ROOT="${ROOT}/scmutils"
SCHEME="${ROOT}/bin/mit-scheme-x86-64"
CMD="${SCHEME} --stack 256 --heap 300000 --edwin --band ${SCMUTILS_ROOT}/scheme-x86-64/mechanics.com"
exec ${CMD}
